SELECT e.first_name, e.last_name, s.salary FROM employees e JOIN salaries s ON e.emp_no = s.emp_no WHERE s.to_date = '9999-01-01';
SELECT e.first_name, e.last_name, d.dept_name FROM employees e JOIN dept_emp de ON e.emp_no = de.emp_no JOIN departments d ON de.dept_no = d.dept_no WHERE de.to_date = '9999-01-01';
SELECT gender, COUNT(*) as count FROM employees GROUP BY gender;
SELECT AVG(salary) as avg_salary FROM salaries WHERE to_date = '9999-01-01';
SELECT d.dept_name, AVG(s.salary) as avg_dept_salary FROM departments d JOIN dept_emp de ON d.dept_no = de.dept_no JOIN salaries s ON de.emp_no = s.emp_no WHERE s.to_date = '9999-01-01' AND de.to_date = '9999-01-01' GROUP BY d.dept_name;
SELECT * FROM employees WHERE last_name REGEXP '^[AB]';
SELECT * FROM employees WHERE first_name REGEXP '(?i)mar';
SELECT emp_no, salary, RANK() OVER (ORDER BY salary DESC) as salary_rank FROM salaries WHERE to_date = '9999-01-01' LIMIT 10;
SELECT de.dept_no, s.emp_no, s.salary, RANK() OVER (PARTITION BY de.dept_no ORDER BY s.salary DESC) as dept_rank FROM salaries s JOIN dept_emp de ON s.emp_no = de.emp_no WHERE s.to_date = '9999-01-01' AND de.to_date = '9999-01-01';
SELECT emp_no, GROUP_CONCAT(title ORDER BY from_date SEPARATOR ', ') as title_history FROM titles GROUP BY emp_no LIMIT 100;
SELECT * FROM employees WHERE hire_date <= DATE_SUB(CURDATE(), INTERVAL 20 YEAR);
SELECT emp_no, from_date, salary, LAG(salary, 1) OVER (PARTITION BY emp_no ORDER BY from_date) as prev_salary, (salary - LAG(salary, 1) OVER (PARTITION BY emp_no ORDER BY from_date)) as difference FROM salaries LIMIT 100;
SELECT emp_no, from_date, salary, LEAD(salary, 1) OVER (PARTITION BY emp_no ORDER BY from_date) as next_salary FROM salaries LIMIT 100;
SELECT e.first_name, e.last_name FROM employees e JOIN dept_manager dm ON e.emp_no = dm.emp_no WHERE dm.to_date = '9999-01-01' AND e.gender = 'F';
WITH CurrentSalaries AS (SELECT salary FROM salaries WHERE to_date = '9999-01-01') SELECT AVG(salary) FROM CurrentSalaries;
WITH DeptAvg AS (SELECT de.dept_no, AVG(s.salary) as avg_sal FROM dept_emp de JOIN salaries s ON de.emp_no = s.emp_no WHERE s.to_date = '9999-01-01' GROUP BY de.dept_no), GlobalAvg AS (SELECT AVG(salary) as glob_sal FROM salaries WHERE to_date = '9999-01-01') SELECT d.dept_name, da.avg_sal FROM DeptAvg da JOIN departments d ON da.dept_no = d.dept_no JOIN GlobalAvg ga WHERE da.avg_sal > ga.glob_sal;
SELECT JSON_OBJECT('id', emp_no, 'name', CONCAT(first_name, ' ', last_name), 'gender', gender) as emp_json FROM employees LIMIT 10;
SELECT emp_no, JSON_ARRAYAGG(title) as titles_json FROM titles GROUP BY emp_no LIMIT 10;
SELECT e.first_name, e.last_name FROM employees e WHERE EXISTS (SELECT 1 FROM dept_emp de WHERE de.emp_no = e.emp_no GROUP BY de.emp_no HAVING COUNT(*) = 1) LIMIT 100;
SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) as rank_dense FROM salaries WHERE to_date = '9999-01-01' LIMIT 20;
SELECT last_name FROM employees WHERE last_name REGEXP 's[eo]n$' LIMIT 50;
SELECT YEAR(from_date) as hire_year, COUNT(*) FROM dept_emp GROUP BY hire_year ORDER BY hire_year;
SELECT emp_no, from_date, salary, SUM(salary) OVER (PARTITION BY emp_no ORDER BY from_date) as running_total_paid FROM salaries LIMIT 100;
SELECT t1.emp_no as Emp1, t2.emp_no as Emp2, t1.title FROM titles t1 JOIN titles t2 ON t1.title = t2.title AND t1.emp_no < t2.emp_no WHERE t1.to_date = '9999-01-01' AND t2.to_date = '9999-01-01' LIMIT 50;
SELECT emp_no, from_date, salary, AVG(salary) OVER (PARTITION BY emp_no ORDER BY from_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as moving_avg FROM salaries LIMIT 100;
SELECT AVG(DATEDIFF(IF(to_date='9999-01-01', CURDATE(), to_date), from_date)) as avg_days_as_manager FROM dept_manager;
SELECT emp_no, birth_date, NTILE(4) OVER (ORDER BY birth_date) as age_quartile FROM employees LIMIT 100;
WITH Stats AS (SELECT AVG(salary) as avg_sal, STDDEV(salary) as std_dev FROM salaries WHERE to_date = '9999-01-01') SELECT s.emp_no, s.salary FROM salaries s, Stats st WHERE s.to_date = '9999-01-01' AND s.salary > (st.avg_sal + 3 * st.std_dev);
SELECT first_name FROM employees WHERE first_name REGEXP '[aeiou]{2}' LIMIT 50;
SELECT SUM(CASE WHEN dept_no = 'd001' THEN 1 ELSE 0 END) as Marketing, SUM(CASE WHEN dept_no = 'd002' THEN 1 ELSE 0 END) as Finance FROM dept_emp WHERE to_date = '9999-01-01';
WITH RECURSIVE DateSeries AS (SELECT '2000-01-01' as d UNION ALL SELECT DATE_ADD(d, INTERVAL 1 YEAR) FROM DateSeries WHERE d < '2010-01-01') SELECT * FROM DateSeries;
SELECT CONCAT(LEFT(first_name, 1), '.', LEFT(last_name, 1), '.') as initials FROM employees LIMIT 50;
SELECT emp_no, salary, FIRST_VALUE(salary) OVER (PARTITION BY emp_no ORDER BY from_date) as starting_salary FROM salaries WHERE to_date = '9999-01-01' LIMIT 50;
SELECT dept_no, COUNT(*) FROM dept_emp WHERE to_date = '9999-01-01' GROUP BY dept_no WITH ROLLUP;
SELECT JSON_EXTRACT(JSON_OBJECT('name', first_name), '$.name') as name_extracted FROM employees LIMIT 10;
SELECT emp_no, salary, PERCENT_RANK() OVER (ORDER BY salary) as percentile FROM salaries WHERE to_date = '9999-01-01' LIMIT 100;
SELECT e.emp_no FROM employees e LEFT JOIN dept_emp de ON e.emp_no = de.emp_no AND de.to_date = '9999-01-01' WHERE de.dept_no IS NULL;
SELECT emp_no, MAX(salary) - MIN(salary) as salary_growth_range FROM salaries GROUP BY emp_no LIMIT 100;
WITH Managers AS (SELECT dept_no, emp_no, from_date, to_date FROM dept_manager) SELECT dept_no, emp_no, LAG(emp_no) OVER (PARTITION BY dept_no ORDER BY from_date) as prev_manager FROM Managers;
SELECT first_name FROM employees WHERE first_name REGEXP '^(.).*\\1$' LIMIT 20;
SELECT salary % 1000 as remainder, COUNT(*) FROM salaries WHERE to_date = '9999-01-01' GROUP BY remainder ORDER BY remainder;
SELECT t.title, d.dept_name, COUNT(*) FROM titles t JOIN dept_emp de ON t.emp_no = de.emp_no JOIN departments d ON de.dept_no = d.dept_no WHERE t.to_date = '9999-01-01' AND de.to_date = '9999-01-01' GROUP BY t.title, d.dept_name;
SELECT * FROM employees WHERE DAYOFWEEK(birth_date) IN (1, 7) LIMIT 50;
SELECT salary, CUME_DIST() OVER (ORDER BY salary) as cum_dist FROM salaries WHERE to_date = '9999-01-01' LIMIT 100;
SELECT emp_no, COUNT(*) OVER (PARTITION BY emp_no) as dept_changes FROM dept_emp LIMIT 100;
SELECT JSON_PRETTY(JSON_OBJECT('id', emp_no, 'dates', JSON_OBJECT('birth', birth_date, 'hire', hire_date))) FROM employees LIMIT 1;
SELECT emp_no, salary, salary * 1.10 as potential_salary FROM salaries WHERE to_date = '9999-01-01';
SELECT emp_no, 'Manager' as type FROM dept_manager WHERE to_date = '9999-01-01' UNION SELECT emp_no, 'Employee' FROM dept_emp WHERE to_date = '9999-01-01' LIMIT 100;
SELECT DISTINCT title FROM titles WHERE title REGEXP 'Engineer|Staff';
WITH MaxDepSal AS (SELECT de.dept_no, MAX(s.salary) as max_sal FROM dept_emp de JOIN salaries s ON de.emp_no = s.emp_no WHERE s.to_date = '9999-01-01' GROUP BY de.dept_no) SELECT de.emp_no, de.dept_no, s.salary FROM dept_emp de JOIN salaries s ON de.emp_no = s.emp_no JOIN MaxDepSal mds ON de.dept_no = mds.dept_no AND s.salary = mds.max_sal WHERE s.to_date = '9999-01-01';
SELECT * FROM employees ORDER BY RAND() LIMIT 5;
SELECT emp_no, salary FROM salaries WHERE (salary & 1) = 0 LIMIT 20;
SELECT emp_no, COUNT(DISTINCT dept_no) as nb_depts FROM dept_emp GROUP BY emp_no HAVING nb_depts > 2;
SELECT * FROM employees WHERE SOUNDEX(last_name) = SOUNDEX('Schwarzenegger');
WITH Duplicates AS (SELECT *, ROW_NUMBER() OVER(PARTITION BY emp_no, from_date ORDER BY to_date DESC) as rn FROM salaries) SELECT * FROM Duplicates WHERE rn > 1;
SELECT JSON_ARRAYAGG(dept_name) FROM departments;
SELECT emp_no, TIMESTAMPDIFF(YEAR, birth_date, CURDATE()) as age FROM employees LIMIT 50;
SELECT CASE WHEN salary < 50000 THEN 'Low' WHEN salary BETWEEN 50000 AND 100000 THEN 'Medium' ELSE 'High' END as category, COUNT(*) FROM salaries WHERE to_date = '9999-01-01' GROUP BY category;
SELECT DISTINCT title FROM titles WHERE title NOT REGEXP '[0-9]';
SELECT table_name, round(((data_length + index_length) / 1024 / 1024), 2) as size_mb FROM information_schema.tables WHERE table_schema = 'employees';